codecov:
  notify:
    require_ci_to_pass: true
comment: false
coverage:
  precision: 2
  range:
  - 70.0
  - 100.0
  round: down
  status:
    project: true
    patch: true
    changes: false
parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false
  javascript:
    enable_partials: false
